# Generated by Django 5.2 on 2025-04-25 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('guessed_letters', models.TextField(default='')),
                ('wrong_guesses', models.IntegerField(default=0)),
                ('max_worng_guesses', models.IntegerField()),
                ('status', models.CharField(choices=[('InProgress', 'In Progress'), ('Won', 'Won'), ('Lost', 'Lost')], default='InPrgress', max_length=20)),
            ],
        ),
    ]
