# Generated by Django 5.2 on 2025-04-26 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='max_worng_guesses',
            new_name='max_wrong_guesses',
        ),
    ]
