# Generated by Django 5.2 on 2025-04-26 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_rename_max_worng_guesses_game_max_wrong_guesses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('InProgress', 'In Progress'), ('Won', 'Won'), ('Lost', 'Lost')], default='InProgress', max_length=20),
        ),
    ]
